#RPM3 features
calls-enabled: true
jobs-enabled: true
month: 1
year: 2388
days-per-month: 20
months-per-season: 1 #full year is a cycle of 4 seasons. Once winter starts, a new year begins.
current-day: 1


#Seasons expansion
seasons-enabled: true

current-season: 'Summer'
int-season: 1
saved-season: 'Summer'
namespace: "rpm" #used as namespace of your datapack containing seasons' biomes.
summer-name: "summer" #name of the summer biome that will be used when summer comes
autumn-name: "autumn" #name of the autumn biome that will be used when autumn comes
winter-name: "winter" #name of the winter biome that will be used when winter comes
spring-name: "spring" #name of the spring biome that will be used when spring comes
#Default values are used in the datapack I provide with plugin. It's free. Downloaded separately

#Message distances
NoneRPDistance: 30
ActionDistance: 25
EnvironmentDistance: 25
ShoutDistance: 70
WhisperDistance: 5
ChatDistance: 35

#HEX colors of messages
NRP_color: '#7e7e7e'
Global_color: '#ffabec'
Action_color: '#f8ffab'
Environment_color: '#f6f6f6'
Shout_color: '#ff5353'
Whisper_color: '#313733'
Chat_color: '#b5d2d8'

#Localization
Language: 'ru.yml'